// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddoihmeqpjjiumqndjgk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkb2lobWVxcGpqaXVtcW5kamdrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2OTc3MDQsImV4cCI6MjA3NDI3MzcwNH0.QsoMKHAYB8yEydI6B_lpTFAaAo52mv5yanzxt8ph-Ho";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});